GET http://localhost:8080/api/matches/
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhMWU1MjEzMDVmNGI2ZGYxZjdlMDQiLCJpYXQiOjE2NTMyMjA2NzcsImV4cCI6MTY1NDUxNjY3N30.x7LoUgr8Q0hnJWhkPEdpwirIAKwydwKtUadCWjac6dQ
###

POST http://localhost:8080/api/matches/
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUxNWE1MjBlZjVmYWY5ZDAzMWYiLCJpYXQiOjE2NTE0MTc4MDMsImV4cCI6MTY1MjcxMzgwM30.FWKo4PkKS5f7UQELopMa2_Du80tiVrwMgAxWDlNK_u0

{
    "players": [null, null, null, null],
    "minLevel": 3.9,
    "maxLevel": 5.9,
    "date": "Tue, 16 May 2022 21:00:00 GMT"
}

###
PATCH http://localhost:8080/api/matches/joinToMatch/627ec1f4455cd6f71df9597e&2
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTI0NzQyNDksImV4cCI6MTY1Mzc3MDI0OX0.eRfBNIKQLvidxLTfATsyLgxtnkQgl6-hDgdD3a8WOW4

###
PATCH http://localhost:8080/api/matches/leaveMatch/627ec1f4455cd6f71df9597e
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTI0NzQyNDksImV4cCI6MTY1Mzc3MDI0OX0.eRfBNIKQLvidxLTfATsyLgxtnkQgl6-hDgdD3a8WOW4
