POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "sergio1",
    "email": "sergio1@sergio1.es",
    "password": "12345",
    "name": "Sergio",
    "surname": "Martinez",
    "gender": "male",
    "position": "peepo",
    "level": 1
}