GET http://localhost:8080/api/matches/
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUzYWE1MjBlZjVmYWY5ZDAzMjIiLCJpYXQiOjE2NTAwMjk4ODksImV4cCI6MTY1MTMyNTg4OX0.1iynYvQ5RMzvXhvo7pgCtCu4QRNPA2WrGDy8XFSvs4k
###

POST http://localhost:8080/api/matches/
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUzYWE1MjBlZjVmYWY5ZDAzMjIiLCJpYXQiOjE2NTAwMjk4ODksImV4cCI6MTY1MTMyNTg4OX0.1iynYvQ5RMzvXhvo7pgCtCu4QRNPA2WrGDy8XFSvs4k

{
    "players": [null, null, null, null],
    "minLevel": 3.9,
    "date": 1651085996454
}