GET http://localhost:8080/api/tournaments/
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTMyMDc2NzksImV4cCI6MTY1NDUwMzY3OX0.25IiAO8YeUOR80o0j_I6hskdsdNr0s4ou_tSf5JBrhA
###

POST http://localhost:8080/api/tournaments/125415
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTMyMDc2NzksImV4cCI6MTY1NDUwMzY3OX0.25IiAO8YeUOR80o0j_I6hskdsdNr0s4ou_tSf5JBrhA

{
    "username": [null, null, null, null, null, null, null, null],
    "quarterFinal": [null, null, null, null],
    "semiFinals": [null, null],
    "final": null
}
###