GET http://localhost:8080/api/users/
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTMyMDc2NzksImV4cCI6MTY1NDUwMzY3OX0.25IiAO8YeUOR80o0j_I6hskdsdNr0s4ou_tSf5JBrhA
###

GET http://localhost:8080/getAllUsernamesAndEmails
###

GET http://localhost:8080/api/users/getAllFriends
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTMyMDc2NzksImV4cCI6MTY1NDUwMzY3OX0.25IiAO8YeUOR80o0j_I6hskdsdNr0s4ou_tSf5JBrhA
###

GET http://localhost:8080/api/users/getInvitedMatches
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhMWU3ZjEzMDVmNGI2ZGYxZjdlMDkiLCJpYXQiOjE2NTMzMzM0NjksImV4cCI6MTY1NDYyOTQ2OX0.nKy-HaQkm4TZSIqWyEe93r1oVEKTFumn6GjxuZpIeMk
###

GET http://localhost:8080/api/users/getUserMatches
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhMWU1MjEzMDVmNGI2ZGYxZjdlMDQiLCJpYXQiOjE2NTM0MTEzNTgsImV4cCI6MTY1NDcwNzM1OH0.lnJzi3u39YeAndJ5fSuUKy38Ye48QNgLKFsyDXmjbvg
###

POST http://localhost:8080/api/users
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUxNWE1MjBlZjVmYWY5ZDAzMWYiLCJpYXQiOjE2NTE0MTc4MDMsImV4cCI6MTY1MjcxMzgwM30.FWKo4PkKS5f7UQELopMa2_Du80tiVrwMgAxWDlNK_u0

{
    "username": "alvaro",
    "email": "alvaro@alvaro.es",
    "password": "12345",
    "name": "Alvaro",
    "surname": "Martinez",
    "gender": "male",
    "level": 2,
    "friends": [],
    "friendsRequest": []
}

###

DELETE  http://localhost:8080/api/users/627c0594480da576a217af86
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUxNWE1MjBlZjVmYWY5ZDAzMWYiLCJpYXQiOjE2NTE0MTc4MDMsImV4cCI6MTY1MjcxMzgwM30.FWKo4PkKS5f7UQELopMa2_Du80tiVrwMgAxWDlNK_u0


### 

PATCH http://localhost:8080/api/users/627164753a9521e0250b10d2
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUxNWE1MjBlZjVmYWY5ZDAzMWYiLCJpYXQiOjE2NTE0MTc4MDMsImV4cCI6MTY1MjcxMzgwM30.FWKo4PkKS5f7UQELopMa2_Du80tiVrwMgAxWDlNK_u0

{
    "password": "12345"
}

###

GET http://localhost:8080/api/users/getUserFromToken
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTMyMDc2NzksImV4cCI6MTY1NDUwMzY3OX0.25IiAO8YeUOR80o0j_I6hskdsdNr0s4ou_tSf5JBrhA

###
PATCH http://localhost:8080/api/users/sendFriendRequest/6259753aa520ef5faf9d0322
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUxNWE1MjBlZjVmYWY5ZDAzMWYiLCJpYXQiOjE2NTAxMzA2NzUsImV4cCI6MTY1MTQyNjY3NX0.4SAVtDBiGQRoS5Y31AanOhaJg90aCYaseZw8XSaOu3o
###
PATCH http://localhost:8080/api/users/acceptFriendRequest/62597515a520ef5faf9d031f
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUzYWE1MjBlZjVmYWY5ZDAzMjIiLCJpYXQiOjE2NTAxMzA3MzUsImV4cCI6MTY1MTQyNjczNX0.jLsveP28Y4V-njcJVa8lz9x57GD0E9PTTu1_XNjzJEI
###
PATCH http://localhost:8080/api/users/removeFriend/6259753aa520ef5faf9d0322
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjU5NzUxNWE1MjBlZjVmYWY5ZDAzMWYiLCJpYXQiOjE2NTAwMjk4NTYsImV4cCI6MTY1MTMyNTg1Nn0.bsIRU34_toPYOwB2cvsg8-G9bAieQAC6x9Hq1-q2VYA
###
PATCH http://localhost:8080/api/users/sendMatchInvitation/628a1ef41305f4b6df1f7e18&628a1e7f1305f4b6df1f7e09
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjcxNjQ3NTNhOTUyMWUwMjUwYjEwZDIiLCJpYXQiOjE2NTI0NzQyNDksImV4cCI6MTY1Mzc3MDI0OX0.eRfBNIKQLvidxLTfATsyLgxtnkQgl6-hDgdD3a8WOW4
